### ISSUE TITLE
MultiDimensionalFitnessFunction evaluates objectives prior to constraints

### ISSUE THREAD

**Issue by sherzig** [martin-fleck/momot#1]
In at.ac.tuwien.big.moea.search.fitness.MultiDimensionalFitnessFunction, the method `delegateEvaluation(Solution solution)` evaluates objectives prior to constraints. In practice, this can be a performance problem if objectives are computationally hard to evaluate, and solutions that violate constraints are considered for further analysis.

Is there a particular reason this was done in this order?

**Comment by martin-fleck** [comment]
You are right, this should not be the case. In fact, the evaluation of the objectives can be neglected when the constraints are violated. Thank you for pointing this out. I will have a more detailed look at the implications of changing this and push a fix as soon as I have some time!

**Comment by sherzig** [comment]
Thanks!
