### ISSUE TITLE
Relative path used rather than URI when passing resource location to EMF

### ISSUE THREAD

**Issue by sherzig** [martin-fleck/momot#2]
Hi,

I found that a relative file path is passed to EMF rather than the desired URI. The URI can still be a string, but should be formatted correctly. At least with my EMF version, EMF was unable to load the henshin ruleset by providing just a relative path. The workaround I found was the following:

Rather than:
`transformations = {
        modules = [ "someRules.henshin" ]
}`

What seems to work is:
`transformations = {
        modules = [ URI.createURI(new File("someRules.henshin").getPath().toString(), true).toString() ]
}`

This happens somewhere in the chain of adding Henshin modules.

Sebastian

**Comment by martin-fleck** [comment]
Hi Sebastian,

Thanks for reporting this! I have also noticed something similar at one point that when you adapt the Henshin module through the graphical editor and save it, it automatically changes to a local, relative path. 

I am currently restructuring the repository a bit to support easier development, but as soon as I have finished that, I will have a closer look at the problem. The solution you provided already looks quite promising, so I will check if it makes sense to include it in the framework directly or if this causes any drawbacks. In any case, it may also make sense to report a bug to Henshin directly. 

Thanks again,
Martin
