### ISSUE TITLE
SearchExecutor does not pass ExecutorService correctly

### ISSUE THREAD

**Issue by sjiherzig** [martin-fleck/momot#5]
It looks like SearchExecutor passes a null reference instead of a newly created ExecutorService object:

````java
...
           } else if(getNumberOfThreads() > 1) {
               executorService = Executors.newFixedThreadPool(getNumberOfThreads());
               problem = new DistributedProblem(problem, getExecutorService());
            }
...
`````

It should instead read:

````java
problem = new DistributedProblem(problem, executorService);
````

In the context, `executorService` refers to a local variable. It does not refer to the (private) field `executorService` from the superclass whose value can be accessed using `getExecutorService()`. Hence, calling `getExecutorService()` does not return the newly created `executorService`, but instead null.

**Comment by martin-fleck** [comment]
Hi Sebastian,
You are absolutely right! Thank you very much for the fix, I merged it!
