### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by sjiherzig** [martin-fleck/momot#9]
I noticed that the current release does not yet incorporate MOEA 2.12 - can you trigger a release of a new version? E.g., 2.1.0? The development update site doesn't seem to have this yet either.

Thanks!

**Comment by martin-fleck** [comment]
Hi Sebastian,
Strange, I thought I already did it, but you are absolutely right. Sorry for that! I released the latest version both on the development and stable update site. Could you please check if everything is as expected now? If so, I will close the issue. Thanks!

**Comment by sjiherzig** [comment]
Hi Martin,

It works perfectly now - thanks!

Sebastian
